export type NavButtonName =
  | 'home'
  | 'search'
  | 'notification'
  | 'mention'
  | 'favorite'
  | 'bookmark'
  | 'compose'
  | 'explore'
  | 'local'
  | 'federated'
  | 'list'
  | 'hashtag'
  | 'lives'
  | 'moreMenu'

export { usePreferences } from './settings/index' 